### ISSUE TITLE
Config Suggestion

### ISSUE THREAD

**Issue by currentoor** [untangled-web/untangled-todomvc#3]
This [step](https://github.com/untangled-web/untangled-todomvc#configure-it) requires people to copy around config stuff but I don't understand why this step is even needed.

If we just add `"resources"` to `:resource-paths` then everything in the `resources` directory will be available on the classpath. Then in `todomvc.system` we can get the path simply by

``` clj
(-> (io/resource "config/defaults.edn") .getPath)
```

I feel like this reduces the friction needed to get started with this project and makes more sense. But maybe there's something I'm unaware of?

**Comment by awkay** [comment]
The requirements are:
1. A defaults file must exist, and the data in it is always applied first
2. A disk file is required, and must exist to start. It overrides anything in (1).

The idea is that you don't ever want to start software in production if the system isn't configured. It is a safety measure. The defaults file is "documentation" and defaults. What is configurable?

So, the way it is set up is quite intentional. Loading configuration from classpath makes it impossible to collaborate with others during development, and is pretty hazardous for production.
